# Generated by Django 3.1.14 on 2022-12-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fyle', '0003_expense_workspace'),
        ('workspaces', '0005_exportsettings_credit_card_expense_date'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row_type', models.CharField(default='TRNS', max_length=255)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('account', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('amount', models.FloatField(help_text='Bill amount')),
                ('document_number', models.CharField(default='', max_length=255, null=True)),
                ('memo', models.TextField()),
                ('clear', models.CharField(default='', max_length=255)),
                ('to_print', models.CharField(default='', max_length=255)),
                ('address', models.TextField(default='')),
                ('due_date', models.CharField(default='', max_length=255)),
                ('terms', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_export', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='tasks.accountingexport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(default='SPL', max_length=255)),
                ('split_line_id', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('account', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('amount', models.FloatField(help_text='Bill amount')),
                ('document_number', models.CharField(default='', max_length=255, null=True)),
                ('memo', models.TextField()),
                ('clear', models.CharField(default='', max_length=255)),
                ('quantity', models.CharField(default='', max_length=255)),
                ('reimbursable_expense', models.CharField(max_length=255)),
                ('service_date', models.CharField(default='', max_length=255)),
                ('others', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lineitems', to='qbd.bill')),
                ('expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lineitems', to='fyle.expense')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_lineitems', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'bill_lineitems',
            },
        ),
    ]
