# Generated by Django 3.1.14 on 2022-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbd', '0003_creditcardpurchase_creditcardpurchaselineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpurchase',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpurchaselineitem',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
    ]
