# Generated by Django 3.1.14 on 2022-12-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_accountingexport_file_id'),
        ('fyle', '0003_expense_workspace'),
        ('workspaces', '0006_auto_20221202_1146'),
        ('qbd', '0004_auto_20221205_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(default='TRNS', max_length=255)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('account', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('class_name', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(help_text='Journal amount')),
                ('document_number', models.CharField(default='', max_length=255, null=True)),
                ('memo', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_export', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='tasks.accountingexport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'journals',
            },
        ),
        migrations.CreateModel(
            name='JournalLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(default='SPL', max_length=255)),
                ('split_line_id', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('account', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('class_name', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(help_text='Journal Lineitem amount')),
                ('document_number', models.CharField(default='', max_length=255, null=True)),
                ('memo', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lineitems', to='fyle.expense')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineitems', to='qbd.journal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lineitems', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'journal_lineitems',
            },
        ),
    ]
