# Generated by Django 3.1.14 on 2022-11-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_advancedsetting_exportsettings_fieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FETCHING_REIMBURSABLE_EXPENSES', 'FETCHING_CREDIT_CARD_EXPENSES'), ('EXPORT_BILLS', 'EXPORT_BILLS')], max_length=50)),
                ('task_id', models.CharField(help_text='Django Q task reference', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ENQUEUED', 'ENQUEUED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('FATAL', 'FATAL')], max_length=255)),
                ('errors', models.JSONField(help_text='Fatal Errors', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'accounting_exports',
            },
        ),
    ]
