# Generated by Django 3.1.14 on 2022-12-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingexport',
            name='type',
            field=models.CharField(choices=[('FETCHING_REIMBURSABLE_EXPENSES', 'FETCHING_REIMBURSABLE_EXPENSES'), ('FETCHING_CREDIT_CARD_EXPENSES', 'FETCHING_CREDIT_CARD_EXPENSES'), ('EXPORT_BILLS', 'EXPORT_BILLS')], max_length=50),
        ),
    ]
