# Generated by Django 3.1.14 on 2022-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20221202_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingexport',
            name='file_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
