version: '3.7'

services:
  api:
    build: 
      context: ./
      args: 
        CI: ENABLED
    entrypoint: bash run.sh
    restart: unless-stopped
    user: root
    volumes:
    - ./:/fyle-qbd-api
    - /tmp:/tmp
    ports:
    - 8000:8000
    depends_on:
    - db
    environment: 
      SECRET_KEY: thisisthedjangosecretkey
      ALLOWED_HOSTS: "*"
      DEBUG: "True"
      FYLE_TOKEN_URI: https://localhost:1234/oauth/token
      FYLE_BASE_URL: https://localhost:1234
      API_URL: http://localhost:8000/api
      QBD_DIRECT_API_URL: http://localhost:8011/api
      FYLE_CLIENT_ID: client_id
      FYLE_CLIENT_SECRET: client_secret
      DB_NAME: qbd_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      SENDGRID_API_KEY: dummy
      SENDGRID_EMAIL_FROM: hehe@hehe.com
  db:
    image: "postgres:15"
    environment: 
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data/
volumes:
  data:
