fixtures = {
    'bills': [
        {
            'row_type': 'TRNS',
            'transaction_id': '',
            'transaction_type': 'BILL',
            'date': '2021-04-26',
            'account': 'Accounts Payable',
            'name': 'Shwetabh',
            'class': 'Awesome',
            'amount': 1284.22,
            'document_number': '',
            'memo': 'Reimbursable Expenses by Shwetabh',
            'clear': '',
            'to_print': '',
            'address': '23/11 North Los Robles, Pasadena, California',
            'due_date': '',
            'terms': '',
            'split_lines': [
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'account': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                }
            ]
        }
    ],
    'credit_card_purchases': [
        {
            'row_type': 'TRNS',
            'transaction_id': '',
            'transaction_type': 'CREDIT CARD',
            'date': '2021-04-26',
            'account': 'Visa',
            'name': 'Amazon',
            'class': '',
            'amount': 1284.22,
            'document_number': '',
            'memo': 'Credit Card Expenses by Shwetabh',
            'clear': '',
            'to_print': '',
            'name_is_taxable': '',
            'address_1': '23/11 North Los Robles, Pasadena, California',
            'address_2': '',
            'address_3': '',
            'address_4': '',
            'address_5': '',
            'due_date': '',
            'terms': '',
            'paid': '',
            'ship_via': '',
            'ship_date': '',
            'year_to_date': '',
            'wage_base': '',
            'split_lines': [
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'CREDIT CARD',
                    'date': '2021-04-26',
                    'account': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'price': '',
                    'inventory_item': '',
                    'payment_method': '',
                    'taxable': '',
                    'value_adjustment': '',
                    'reimbursable_expense': 'No',
                    'service_date': '',
                    'others_2': '',
                    'others_3': '',
                    'year_to_date': '',
                    'wage_base': ''
                }
            ]
        },
        {
            'row_type': 'TRNS',
            'transaction_id': '',
            'transaction_type': 'CREDIT CARD',
            'date': '2021-04-26',
            'account': 'Visa',
            'name': 'Olive Garden',
            'class': '',
            'amount': 452.22,
            'document_number': '',
            'memo': 'Credit Card Expenses by Shwetabh',
            'clear': '',
            'to_print': '',
            'name_is_taxable': '',
            'address_1': '23/11 North Los Robles, Pasadena, California',
            'address_2': '',
            'address_3': '',
            'address_4': '',
            'address_5': '',
            'due_date': '',
            'terms': '',
            'paid': '',
            'ship_via': '',
            'ship_date': '',
            'year_to_date': '',
            'wage_base': '',
            'split_lines': [
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'CREDIT CARD',
                    'date': '2021-04-26',
                    'account': 'Food',
                    'name': 'Delloite - 1',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'price': '',
                    'inventory_item': '',
                    'payment_method': '',
                    'taxable': '',
                    'value_adjustment': '',
                    'reimbursable_expense': 'No',
                    'service_date': '',
                    'others_2': '',
                    'others_3': '',
                    'year_to_date': '',
                    'wage_base': ''
                }
            ]
        }
    ],
}
