fixtures = {
    'bills': [
        {
            'row_type': 'TRNS',
            'transaction_id': '',
            'transaction_type': 'BILL',
            'date': '2021-04-26',
            'accounts': 'Accounts Payable',
            'name': 'Shwetabh',
            'class': 'Awesome',
            'amount': 1284.22,
            'document_number': '',
            'memo': 'Reimbursable Expenses by Shwetabh',
            'clear': '',
            'to_print': '',
            'address': '23/11 North Los Robles, Pasadena, California',
            'due_date': '',
            'terms': '',
            'split_lines': [
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                },
                {
                    'row_type': 'SPL',
                    'split_line_id': '',
                    'transaction_type': 'BILL',
                    'date': '2021-04-26',
                    'accounts': 'Food',
                    'name': 'Delloite',
                    'class': 'Awesome',
                    'amount': 1284.22,
                    'document_number': '',
                    'memo': 'Expense on Category - Food',
                    'clear': '',
                    'quantity': '',
                    'reimbursable_expense': 'Yes',
                    'service_date': '',
                    'others': ''
                }
            ]
        }
    ]
}
