# Generated by Django 3.1.14 on 2022-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid_on_xero',
        ),
        migrations.AddField(
            model_name='expense',
            name='exported',
            field=models.BooleanField(default=False, help_text='Expense reimbursable or not'),
        ),
    ]
