# Generated by Django 3.1.14 on 2024-05-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_expense_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settlement_id',
        ),
    ]
