# Generated by Django 3.1.14 on 2024-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='workspace_id',
            field=models.IntegerField(help_text='Workspace id of the organization'),
            preserve_default=False,
        ),
    ]
