# Generated by Django 3.1.14 on 2023-08-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0025_auto_20230825_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBDMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_type', models.CharField(help_text='Type of expense attribute', max_length=255)),
                ('source_value', models.CharField(help_text='Value of expense attribute', max_length=1000)),
                ('source_id', models.CharField(help_text='Fyle ID', max_length=255)),
                ('destination_value', models.CharField(blank=True, help_text='Value of destination attribute', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'qbd_mappings',
            },
        ),
    ]
