# Generated by Django 3.1.14 on 2024-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbdmapping',
            name='source_id',
            field=models.CharField(help_text='Fyle ID', max_length=255, unique=True),
        ),
    ]
