fixtures = {
    'get_my_profile': {
        'data': {
            'org': {
                'currency': 'USD',
                'domain': 'fyleforqvd.com',
                'id': 'orNoatdUnm1w',
                'name': 'Fyle For MS Dynamics Demo',
            },
            'org_id': 'orNoatdUnm1w',
            'roles': [
                'FYLER',
                'VERIFIER',
                'PAYMENT_PROCESSOR',
                'FINANCE',
                'ADMIN',
                'AUDITOR',
            ],
            'user': {
                'email': 'ashwin.t@fyle.in',
                'full_name': 'Joanna',
                'id': 'usqywo0f3nBY'
            },
            'user_id': 'usqywo0f3nBY',
        }
    },
    'reimbursable_expenses': [
        {
            'id': 'tx4ziVSAyIsv',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/3',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/2',
            'amount': 150,
            'tax_amount': 0,
            'tax_group_id': 'tgWdIdEwcKlK',
            'settled_at': '2021-12-23T07:16:17.034079+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'seteYqkAfuWOS',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpqaDywYdbbw',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-23T07:14:13.990650+00:00',
            'expense_updated_at': '2021-12-27T05:26:43.954470+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                  'Vehicle Type': '',
                  'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6wOnBVaumk',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6jajajaj',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tjgjgjgjgjal',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6samskflaskk',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            }
        }
    ],
    'credit_card_expenses': [
        {
            'id': 'tx4ziVSAyIsv',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/3',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/2',
            'amount': 150,
            'tax_amount': 0,
            'tax_group_id': 'tgWdIdEwcKlK',
            'settled_at': '2021-12-23T07:16:17.034079+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'seteYqkAfuWOS',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpqaDywYdbbw',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-23T07:14:13.990650+00:00',
            'expense_updated_at': '2021-12-27T05:26:43.954470+00:00',
            'source_account_type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                  'Vehicle Type': '',
                  'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6wOnBVaumk',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6jajajaj',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tjgjgjgjgjal',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6samskflaskk',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            }
        }
    ]
}