fixtures = {
    'get_my_profile': {
        'data': {
            'org': {
                'currency': 'USD',
                'domain': 'fyleforqvd.com',
                'id': 'orNoatdUnm1w',
                'name': 'Fyle For MS Dynamics Demo',
            },
            'org_id': 'orNoatdUnm1w',
            'roles': [
                'FYLER',
                'VERIFIER',
                'PAYMENT_PROCESSOR',
                'FINANCE',
                'ADMIN',
                'AUDITOR',
            ],
            'user': {
                'email': 'ashwin.t@fyle.in',
                'full_name': 'Joanna',
                'id': 'usqywo0f3nBY'
            },
            'user_id': 'usqywo0f3nBY',
        }
    },
    'reimbursable_expenses': [
        {'count': 6, 'data': [{
            'activity_details': None,
            'added_to_report_at': '2022-05-06T06:31:59.537000+00:00',
            'admin_amount': None,
            'amount': 121,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 121,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-06T06:31:24.215743+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fi0wgxEaXLQq'],
            'files': [{
                'content_type': 'image/jpeg',
                'id': 'fi0wgxEaXLQq',
                'name': 'EufzrTTUcAU6Asq.jpeg',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txcJF5HIGNEe',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': True,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-06T06:32:51.665316+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpdWbicTeBGC',
                'last_approved_at': '2022-05-06T06:32:07.018+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-06T06:32:00.184+00:00',
                'reimbursement_id': 'reimv8ED0Yzxi0',
                'reimbursement_seq_num': 'P/2022/05/R/6',
                'seq_num': 'C/2022/05/R/6',
                'settlement_id': 'set0mrwTTgoHA',
                'state': 'PAYMENT_PROCESSING',
                'title': '#6:  May 2022',
            },
            'report_id': 'rpdWbicTeBGC',
            'seq_num': 'E/2022/05/T/6',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CASH_ACCOUNT'},
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-06T17:00:00+00:00',
            'split_group_id': 'txcJF5HIGNEe',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-06T06:32:51.665316+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T09:54:32.094000+00:00',
            'admin_amount': None,
            'amount': 665,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 665,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T09:54:21.175276+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fiOYeqtsSIyd'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fiOYeqtsSIyd',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txJpgonlZw9z',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': True,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T09:55:14.040636+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpdWbicTeBGC',
                'last_approved_at': '2022-05-05T09:54:38.787+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T09:54:32.4+00:00',
                'reimbursement_id': 'reimIWuET63w9n',
                'reimbursement_seq_num': 'P/2022/05/R/5',
                'seq_num': 'C/2022/05/R/5',
                'settlement_id': 'setfqoiqUVRYd',
                'state': 'PAYMENT_PROCESSING',
                'title': '#5:  May 2022',
            },
            'report_id': 'rpdWbicTeBGC',
            'seq_num': 'E/2022/05/T/5',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CASH_ACCOUNT'},
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txJpgonlZw9z',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T09:55:14.040636+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T09:01:37.283000+00:00',
            'admin_amount': None,
            'amount': 122,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 122,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T09:01:31.535324+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fijdZNsaXXpn'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fijdZNsaXXpn',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txkuA5qRp1S9',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': True,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T09:03:33.334235+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpGH5ed4TDEU',
                'last_approved_at': '2022-05-05T09:01:41.475+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T09:01:37.859+00:00',
                'reimbursement_id': 'reimo1VO1yzyK6',
                'reimbursement_seq_num': 'P/2022/05/R/4',
                'seq_num': 'C/2022/05/R/4',
                'settlement_id': 'setUzZd9WDh4b',
                'state': 'PAYMENT_PROCESSING',
                'title': '#4:  May 2022',
            },
            'report_id': 'rpGH5ed4TDEU',
            'seq_num': 'E/2022/05/T/4',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CASH_ACCOUNT'},
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txkuA5qRp1S9',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T09:03:33.334235+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T08:48:14.766000+00:00',
            'admin_amount': None,
            'amount': 111,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 111,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T08:48:05.279002+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fiu4In8e6Jke'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fiu4In8e6Jke',
                'name': 'Screenshot 2022-04-28 at 10.41.21 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txqoJmP4Cesp',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': True,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T08:49:14.027707+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rplKVKEnGMM9',
                'last_approved_at': '2022-05-05T08:48:40.742+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T08:48:15.812+00:00',
                'reimbursement_id': 'reimThZc9jwVDM',
                'reimbursement_seq_num': 'P/2022/05/R/3',
                'seq_num': 'C/2022/05/R/3',
                'settlement_id': 'set0LnL005MA7',
                'state': 'PAYMENT_PROCESSING',
                'title': '#3:  May 2022',
            },
            'report_id': 'rplKVKEnGMM9',
            'seq_num': 'E/2022/05/T/3',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CASH_ACCOUNT'},
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txqoJmP4Cesp',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T08:49:14.027707+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T08:42:10.425000+00:00',
            'admin_amount': None,
            'amount': 123,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': 'Software',
            },
            'category_id': 114965,
            'claim_amount': 123,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T08:41:55.952630+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fi2ZZTWZkYBx'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fi2ZZTWZkYBx',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txevJ5AUbGhJ',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': True,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T08:44:32.094519+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpa7Lo54Jw2H',
                'last_approved_at': '2022-05-05T08:42:36.783+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T08:42:11.116+00:00',
                'reimbursement_id': 'reimvj3so5zBl7',
                'reimbursement_seq_num': 'P/2022/05/R/2',
                'seq_num': 'C/2022/05/R/2',
                'settlement_id': 'setlBZs14zpck',
                'state': 'PAYMENT_PROCESSING',
                'title': '#2:  May 2022',
            },
            'report_id': 'rpa7Lo54Jw2H',
            'seq_num': 'E/2022/05/T/2',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CASH_ACCOUNT'},
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txevJ5AUbGhJ',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T08:44:32.094519+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }], 'offset': 0}
    ],
    'credit_card_expenses': [
        #!/usr/bin/python
        # -*- coding: utf-8 -*-
        {'count': 6, 'data': [{
            'activity_details': None,
            'added_to_report_at': '2022-05-06T06:31:59.537000+00:00',
            'admin_amount': None,
            'amount': 121,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 121,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-06T06:31:24.215743+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fi0wgxEaXLQq'],
            'files': [{
                'content_type': 'image/jpeg',
                'id': 'fi0wgxEaXLQq',
                'name': 'EufzrTTUcAU6Asq.jpeg',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txcJF5HIGNEe',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': False,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-06T06:32:51.665316+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpdWbicTeBGC',
                'last_approved_at': '2022-05-06T06:32:07.018+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-06T06:32:00.184+00:00',
                'reimbursement_id': 'reimv8ED0Yzxi0',
                'reimbursement_seq_num': 'P/2022/05/R/6',
                'seq_num': 'C/2022/05/R/6',
                'settlement_id': 'set0mrwTTgoHA',
                'state': 'PAYMENT_PROCESSING',
                'title': '#6:  May 2022',
            },
            'report_id': 'rpdWbicTeBGC',
            'seq_num': 'E/2022/05/T/6',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
                               },
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-06T17:00:00+00:00',
            'split_group_id': 'txcJF5HIGNEe',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-06T06:32:51.665316+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T09:54:32.094000+00:00',
            'admin_amount': None,
            'amount': 665,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 665,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T09:54:21.175276+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fiOYeqtsSIyd'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fiOYeqtsSIyd',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txJpgonlZw9z',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': False,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T09:55:14.040636+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpHBOa6Ybmof',
                'last_approved_at': '2022-05-05T09:54:38.787+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T09:54:32.4+00:00',
                'reimbursement_id': 'reimIWuET63w9n',
                'reimbursement_seq_num': 'P/2022/05/R/5',
                'seq_num': 'C/2022/05/R/5',
                'settlement_id': 'setfqoiqUVRYd',
                'state': 'PAYMENT_PROCESSING',
                'title': '#5:  May 2022',
            },
            'report_id': 'rpHBOa6Ybmof',
            'seq_num': 'E/2022/05/T/5',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
                               },
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txJpgonlZw9z',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T09:55:14.040636+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T09:01:37.283000+00:00',
            'admin_amount': None,
            'amount': 122,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 122,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T09:01:31.535324+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fijdZNsaXXpn'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fijdZNsaXXpn',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txkuA5qRp1S9',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': False,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T09:03:33.334235+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpGH5ed4TDEU',
                'last_approved_at': '2022-05-05T09:01:41.475+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T09:01:37.859+00:00',
                'reimbursement_id': 'reimo1VO1yzyK6',
                'reimbursement_seq_num': 'P/2022/05/R/4',
                'seq_num': 'C/2022/05/R/4',
                'settlement_id': 'setUzZd9WDh4b',
                'state': 'PAYMENT_PROCESSING',
                'title': '#4:  May 2022',
            },
            'report_id': 'rpGH5ed4TDEU',
            'seq_num': 'E/2022/05/T/4',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
                               },
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txkuA5qRp1S9',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T09:03:33.334235+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T08:48:14.766000+00:00',
            'admin_amount': None,
            'amount': 111,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': None,
            },
            'category_id': 114965,
            'claim_amount': 111,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T08:48:05.279002+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fiu4In8e6Jke'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fiu4In8e6Jke',
                'name': 'Screenshot 2022-04-28 at 10.41.21 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txqoJmP4Cesp',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': False,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T08:49:14.027707+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpa7Lo54Jw2H',
                'last_approved_at': '2022-05-05T08:48:40.742+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T08:48:15.812+00:00',
                'reimbursement_id': 'reimThZc9jwVDM',
                'reimbursement_seq_num': 'P/2022/05/R/3',
                'seq_num': 'C/2022/05/R/3',
                'settlement_id': 'set0LnL005MA7',
                'state': 'PAYMENT_PROCESSING',
                'title': '#3:  May 2022',
            },
            'report_id': 'rpa7Lo54Jw2H',
            'seq_num': 'E/2022/05/T/3',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
                               },
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txqoJmP4Cesp',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T08:49:14.027707+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }, {
            'activity_details': None,
            'added_to_report_at': '2022-05-05T08:42:10.425000+00:00',
            'admin_amount': None,
            'amount': 123,
            'approvals': [{'approver_user': {'email': 'ashwin.t@fyle.in',
                                             'full_name': 'Ashwin', 'id': 'usqywo0f3nBY'},
                           'approver_user_id': 'usqywo0f3nBY',
                           'state': 'APPROVAL_DONE'}],
            'category': {
                'code': None,
                'id': 114965,
                'name': 'Software',
                'sub_category': 'Software',
            },
            'category_id': 114965,
            'claim_amount': 123,
            'code': None,
            'cost_center': None,
            'cost_center_id': None,
            'created_at': '2022-05-05T08:41:55.952630+00:00',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'custom_fields': [{'name': 'Custom Expense Field', 'value': None},
                              {'name': 'Quickbooks Class', 'value': ''},
                              {'name': 'Quickbooks Customer', 'value': ''},
                              {'name': 'Team', 'value': ''},
                              {'name': 'Operating System', 'value': ''}],
            'distance': None,
            'distance_unit': None,
            'employee': {
                'code': None,
                'department': None,
                'department_id': None,
                'id': 'ouJSY9XI9s9k',
                'org_id': 'orNoatdUnm1w',
                'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                         'id': 'usqywo0f3nBY'},
                'user_id': 'usqywo0f3nBY',
            },
            'employee_id': 'ouJSY9XI9s9k',
            'ended_at': None,
            'extracted_data': None,
            'file_ids': ['fi2ZZTWZkYBx'],
            'files': [{
                'content_type': 'image/png',
                'id': 'fi2ZZTWZkYBx',
                'name': 'Screenshot 2022-04-28 at 10.41.35 PM.png',
                'type': 'RECEIPT',
            }],
            'foreign_amount': None,
            'foreign_currency': None,
            'hotel_is_breakfast_provided': False,
            'id': 'txevJ5AUbGhJ',
            'is_billable': False,
            'is_corporate_card_transaction_auto_matched': False,
            'is_exported': None,
            'is_manually_flagged': None,
            'is_physical_bill_submitted': None,
            'is_policy_flagged': None,
            'is_receipt_mandatory': None,
            'is_reimbursable': False,
            'is_verified': False,
            'last_exported_at': None,
            'last_settled_at': '2022-05-05T08:44:32.094519+00:00',
            'last_verified_at': None,
            'locations': [],
            'matched_corporate_card_transaction_ids': [],
            'matched_corporate_card_transactions': [],
            'merchant': None,
            'mileage_calculated_amount': None,
            'mileage_calculated_distance': None,
            'mileage_is_round_trip': None,
            'mileage_rate': None,
            'mileage_rate_id': None,
            'missing_mandatory_fields': {'amount': False, 'currency': False,
                                         'expense_field_ids': []},
            'org_id': 'orNoatdUnm1w',
            'per_diem_num_days': None,
            'per_diem_rate': None,
            'per_diem_rate_id': None,
            'physical_bill_submitted_at': None,
            'policy_amount': None,
            'project': None,
            'project_id': None,
            'purpose': None,
            'report': {
                'id': 'rpa7Lo54Jw2H',
                'last_approved_at': '2022-05-05T08:42:36.783+00:00',
                'last_paid_at': None,
                'last_submitted_at': '2022-05-05T08:42:11.116+00:00',
                'reimbursement_id': 'reimvj3so5zBl7',
                'reimbursement_seq_num': 'P/2022/05/R/2',
                'seq_num': 'C/2022/05/R/2',
                'settlement_id': 'setlBZs14zpck',
                'state': 'PAYMENT_PROCESSING',
                'title': '#2:  May 2022',
            },
            'report_id': 'rpa7Lo54Jw2H',
            'seq_num': 'E/2022/05/T/2',
            'source': 'WEBAPP',
            'source_account': {'id': 'accdufDBSQaCi',
                               'type': 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
                               },
            'source_account_id': 'accdufDBSQaCi',
            'spent_at': '2022-05-05T17:00:00+00:00',
            'split_group_id': 'txevJ5AUbGhJ',
            'started_at': None,
            'state': 'PAYMENT_PROCESSING',
            'state_display_name': None,
            'tax_amount': None,
            'tax_group_id': None,
            'travel_classes': [],
            'updated_at': '2022-05-05T08:44:32.094519+00:00',
            'user': {'email': 'ashwin.t@fyle.in', 'full_name': 'Ashwin',
                     'id': 'usqywo0f3nBY'},
            'user_id': 'usqywo0f3nBY',
        }], 'offset': 0}
    ],
    'create_file': {
        'data': {
            'content_type': None,
            'created_at': '2022-12-02T05:54:49.217696+00:00',
            'id': 'fimNloQVF0D8',
            'name': 'bills.iif',
            'org_id': 'orFcbTXP4Nzl',
            'type': 'INTEGRATION',
            'updated_at': '2022-12-02T05:54:49.217696+00:00',
            'user_id': 'uswxaNAqh20T'
        }
    },
    'generate_file_urls': {
        'data': [
            {
                'content_type': None,
                'download_url': 'https://fyle-storage-mumbai-3.s3.amazonaws.com/2022-12-02/orFcbTXP4Nzl/integrations/fimNloQVF0D8.bills.iif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA54Z3LIXTX6CFH4VG%2F20221202%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20221202T090102Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=049855502d50779c694eb1df93f19a3c2e5386410cce9f337dfa127beddd2140',
                'id': 'fimNloQVF0D8',
                'name': 'bills.iif',
                'upload_url': 'https://fyle-storage-mumbai-3.s3.amazonaws.com/2022-12-02/orFcbTXP4Nzl/integrations/fimNloQVF0D8.bills.iif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA54Z3LIXTX6CFH4VG%2F20221202%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20221202T090102Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b9e0943a61356cb8e85b2eaeee0df5464e3450d820387c19a984a132e6a5bd83'
            }
        ]
    }
}
