# Generated by Django 3.1.14 on 2022-11-30 10:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_fylecredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('class_type', models.CharField(help_text='Class Mapped to Fyle Field', max_length=255)),
                ('project_type', models.CharField(help_text='Project Mapped to Fyle Field', max_length=255)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'field_mapping',
            },
        ),
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('reimbursable_expenses_export_type', models.CharField(choices=[('BILL', 'BILL'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], max_length=255)),
                ('bank_account_name', models.CharField(help_text='Bank account name', max_length=255)),
                ('reimbursable_expense_state', models.CharField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], max_length=255)),
                ('reimbursable_expense_date', models.CharField(choices=[('LAST_SPEND_DATE', 'last_spent_at'), ('CREATED_DATE', 'created_at'), ('SPEND DATE', 'spent_at')], max_length=255)),
                ('reimbursable_expense_grouped_by', models.CharField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], max_length=255)),
                ('credit_card_expense_export_type', models.CharField(choices=[('JOURNAL_ENTRY', 'JOURNAL_ENTRY'), ('CREDIT_CARD_CHARGE', 'CREDIT_CARD_CHARGE')], max_length=255)),
                ('credit_card_expense_state', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], max_length=255)),
                ('credit_card_account_name', models.CharField(help_text='Credit card account name', max_length=255)),
                ('credit_card_expense_grouped_by', models.CharField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], max_length=255)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'export_settings',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('memo_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of fields in memo', size=None)),
                ('schedule_is_enabled', models.BooleanField(help_text='Boolean to check if schedule is enabled')),
                ('interval_hours', models.IntegerField(help_text='Interval hours for schedule')),
                ('schedule_id', models.CharField(help_text='Schedule id', max_length=255)),
                ('emails_selected', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of emails_selected', size=None)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'advanced_settings',
            },
        ),
    ]
