# Generated by Django 3.1.14 on 2022-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_advancedsetting_exportsettings_fieldmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='last_synced_at',
        ),
        migrations.AddField(
            model_name='workspace',
            name='ccc_last_synced_at',
            field=models.DateTimeField(help_text='Datetime when credit card expenses were pulled last', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reimbursable_last_synced_at',
            field=models.DateTimeField(help_text='Datetime when reimbursable expenses were pulled last', null=True),
        ),
    ]
