# Generated by Django 3.1.14 on 2022-12-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20221130_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsettings',
            name='credit_card_expense_date',
            field=models.CharField(choices=[('LAST_SPEND_DATE', 'last_spent_at'), ('CREATED_DATE', 'created_at'), ('SPEND DATE', 'spent_at')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
