# Generated by Django 3.1.14 on 2022-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_exportsettings_credit_card_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedsetting',
            name='interval_hours',
            field=models.IntegerField(help_text='Interval hours for schedule', null=True),
        ),
        migrations.AlterField(
            model_name='advancedsetting',
            name='schedule_id',
            field=models.CharField(help_text='Schedule id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advancedsetting',
            name='schedule_is_enabled',
            field=models.BooleanField(default=False, help_text='Boolean to check if schedule is enabled'),
        ),
    ]
