# Generated by Django 3.1.14 on 2022-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20221202_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsettings',
            name='credit_card_enity_name_preference',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('VENDOR', 'VENDOR')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
