# Generated by Django 3.1.14 on 2022-12-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_exportsettings_credit_card_enity_name_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsettings',
            old_name='credit_card_enity_name_preference',
            new_name='credit_card_entity_name_preference',
        ),
    ]
