# Generated by Django 3.1.14 on 2022-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_auto_20221206_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='cluster_domain',
        ),
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(help_text='fyle currency', max_length=255, null=True),
        ),
    ]
