# Generated by Django 3.1.14 on 2022-12-07 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_auto_20221207_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedsetting',
            name='memo_structure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of fields in memo', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_account_name',
            field=models.CharField(help_text='Credit card account name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_entity_name_preference',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('VENDOR', 'VENDOR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_expense_date',
            field=models.CharField(choices=[('LAST_SPEND_DATE', 'last_spent_at'), ('SPEND DATE', 'spent_at'), ('CURRENT_DATE', 'current_date')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_expense_export_type',
            field=models.CharField(choices=[('JOURNAL_ENTRY', 'JOURNAL_ENTRY'), ('CREDIT_CARD_CHARGE', 'CREDIT_CARD_CHARGE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_expense_grouped_by',
            field=models.CharField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_expense_state',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='reimbursable_expense_date',
            field=models.CharField(choices=[('LAST_SPEND_DATE', 'last_spent_at'), ('CREATED_DATE', 'created_at'), ('SPEND DATE', 'spent_at')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='reimbursable_expense_grouped_by',
            field=models.CharField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='reimbursable_expense_state',
            field=models.CharField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='reimbursable_expenses_export_type',
            field=models.CharField(choices=[('BILL', 'BILL'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='class_type',
            field=models.CharField(help_text='Class Mapped to Fyle Field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='project_type',
            field=models.CharField(help_text='Project Mapped to Fyle Field', max_length=255, null=True),
        ),
    ]
