# Generated by Django 3.1.14 on 2022-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20221207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsettings',
            name='bank_account_name',
            field=models.CharField(help_text='Bank account name', max_length=255, null=True),
        ),
    ]
