# Generated by Django 3.1.14 on 2023-01-17 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_auto_20221207_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedsetting',
            old_name='memo_structure',
            new_name='expense_memo_structure',
        ),
        migrations.AddField(
            model_name='advancedsetting',
            name='top_memo_structure',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                help_text='Array of fields in memo', null=True, size=None
            ),
        ),
    ]
