# Generated by Django 3.1.14 on 2023-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_exportsettings_is_simplify_report_closure_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsettings',
            name='mileage_account_name',
            field=models.CharField(help_text='Mileage account name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='credit_card_expense_date',
            field=models.CharField(choices=[('last_spent_at', 'last_spent_at'), ('spent_at', 'spent_at'), ('posted_at', 'posted_at'), ('created_at', 'created_at')], max_length=255, null=True),
        ),
    ]
