# Generated by Django 3.1.14 on 2023-09-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_auto_20230823_1118'),
        ('workspaces', '0025_auto_20230825_1040'),
    ]

    operations = [
    ]
