# Generated by Django 3.1.14 on 2024-07-19 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_auto_20231006_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='custom_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='item_type',
            field=models.CharField(help_text='Item Mapped to Fyle Field', max_length=255, null=True),
        ),
    ]
