# Generated by Django 3.1.14 on 2024-12-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0027_auto_20240719_0948'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE workspaces_user
                ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE workspaces_user
                DROP COLUMN created_at;
            """,
        ),
    ]
