# Generated by Django 3.1.14 on 2025-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0028_add_created_at_to_user_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='migrated_to_qbd_direct',
            field=models.BooleanField(default=False, help_text='Migrated to QBD Direct'),
        ),
    ]
